INVOICE_STATUS_DRAFT = "DRAFT"
INVOICE_STATUS_SENT = "SENT"
INVOICE_STATUS_PAID = "PAID"
INVOICE_STATUS_PARTIAL = "PARTIAL"
INVOICE_STATUS_OVERDUE = "OVERDUE"
INVOICE_STATUS_VOID = "VOID"

PAYMENT_STATUS_SUCCEEDED = "SUCCEEDED"
PAYMENT_STATUS_PENDING = "PENDING"
PAYMENT_STATUS_FAILED = "FAILED"

PAYMENT_METHOD_CASH = "cash"
PAYMENT_METHOD_ETRANSFER = "etransfer"
PAYMENT_METHOD_OTHER = "other"


def normalize_status(value: str) -> str:
    return value.upper()
